"""create narrative and action tables

Revision ID: f690d2293bd0
Revises: 0d1c4dfe40e7
Create Date: 2026-05-19 02:54:31.153289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f690d2293bd0'
down_revision: Union[str, Sequence[str], None] = '0d1c4dfe40e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('narrative',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_narrative_id'), 'narrative', ['id'], unique=False)
    op.create_table('detected_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('target', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('narrative_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['narrative_id'], ['narrative.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detected_action_id'), 'detected_action', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detected_action_id'), table_name='detected_action')
    op.drop_table('detected_action')
    op.drop_index(op.f('ix_narrative_id'), table_name='narrative')
    op.drop_table('narrative')
    # ### end Alembic commands ###
